name: Terraform plan

permissions:
  contents: 'read'
  id-token: 'write'
  pull-requests: 'write'

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'plan対象のブランチ名'
        type: string
        required: true
      target_env:
        description: 'plan対象のenv名'
        type: string
        default: dev
        required: true
  pull_request:
    branches:
      - 'main'
    paths:
      - 'terraform/*.tf'
    types: [opened, synchronize, reopened]

env:
  GCP_WORKLOAD_IDENTITY: ${{ secrets.GCP_WORKLOAD_IDENTITY }}
  GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
  TF_VERSION: 1.12.2
  TF_WORK_DIR: "terraform/"
  TF_ENV: ${{ (github.event_name == 'pull_request' && 'dev') || github.event.inputs.target_env }}

defaults:
  run:
    shell: bash
    working-directory: ./terraform

jobs:
  plan:
    name: Terraform plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.target_branch || github.ref }}

      # Authenticate to Google Cloud
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
          access_token_lifetime: 1200s

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format
        working-directory: ${{ env.TF_WORK_DIR }}
        run: terraform fmt -recursive -check -diff

      - name: Terraform Init
        working-directory: ${{ env.TF_WORK_DIR }}
        run: terraform init -input=false -no-color -reconfigure

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORK_DIR }}
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        working-directory: ${{ env.TF_WORK_DIR }}
        run: terraform plan -no-color -input=false -var-file="env/${{ env.TF_ENV }}.tfvars" -out=tfplan.binary
        continue-on-error: true

      - name: Convert plan to text
        id: plan-text
        run: |
          if [[ ${{ steps.plan.outcome }} == 'failure' && ${{ steps.plan.exit_code }} != 2 ]]; then
            echo "TERRAFORM_PLAN<<EOF" >> $GITHUB_OUTPUT
            echo "Terraform Plan failed." >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          terraform show -no-color tfplan.binary > plan.txt

          PLAN_CONTENT=$(cat plan.txt)
          echo "TERRAFORM_PLAN<<EOF" >> $GITHUB_OUTPUT
          echo "$PLAN_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create or Update PR Comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ github.run_id }}
          body: |
            ### Terraform Plan Result
            **${{ steps.plan.outcome == 'success' && '✅ Plan: No changes' || (steps.plan.exit_code == 2 && '⚠️ Plan: Changes detected' || '❌ Plan: Failed') }}**

            <details><summary>Show Plan Details</summary>

            \`\`\`terraform
            ${{ steps.plan-text.outputs.TERRAFORM_PLAN }}
            \`\`\`

            </details>

            ---
            *Triggered by: \`${{ github.event_name }}\` on commit `${{ github.sha }}` by @${{ github.actor }}*
